# .github/FUNDING.yml

github: [juniyasyos]          
patreon:                       
open_collective:               
ko_fi: juniyasyos            
tidelift:                      
community_bridge:             
liberapay:                    
issuehunt:                     
lfx_crowdfunding:             
polar:                        
thanks_dev:                    
custom: ['https://trakteer.id/si_dahlan_%28dahlan%29'] 
