# .github/FUNDING.yml

github: [juniyasyos]          
patreon:                       
open_collective:               
ko_fi: juniyasyos            
tidelift:                      
community_bridge:             
liberapay:                    
issuehunt:                     
lfx_crowdfunding:             
polar:                         
buy_me_a_coffee: juniyasyos   
thanks_dev:                    
custom: ['https://trakteer.id/juniyasyos']
